# Generated by Django 4.2.3 on 2023-07-05 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='sets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('h_image', models.ImageField(upload_to='setting_images')),
                ('g_image', models.ImageField(upload_to='setting_images')),
            ],
        ),
        migrations.CreateModel(
            name='signature',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classs', models.CharField(max_length=100)),
                ('t_image', models.ImageField(upload_to='signs')),
                ('p_image', models.ImageField(upload_to='signs')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=True, null=True)),
                ('gender', models.CharField(max_length=100, null=True)),
                ('category', models.CharField(choices=[('Normal', 'Normal'), ('Complement', 'Complement'), ('Schoolarship', 'Schoolarship'), ('Dependant', 'Dependant')], default='Normal', max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ('class_name',),
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StudentResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ca1', models.IntegerField(default=0)),
                ('ca2', models.IntegerField(default=0)),
                ('exams', models.IntegerField(default=0)),
                ('total', models.IntegerField(default=0)),
                ('subject_position', models.IntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.student')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.studentclass')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.subject')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.term')),
            ],
            options={
                'ordering': ['session'],
            },
        ),
        migrations.CreateModel(
            name='StudentBehaviouralAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conduct', models.IntegerField(default=0)),
                ('punctuality', models.IntegerField(default=0)),
                ('dedication', models.IntegerField(default=0)),
                ('participation', models.IntegerField(default=0)),
                ('hospitality', models.IntegerField(default=0)),
                ('neatness', models.IntegerField(default=0)),
                ('creativity', models.IntegerField(default=0)),
                ('physical', models.IntegerField(default=0)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.student')),
                ('student_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.studentclass')),
                ('term', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='src.term')),
            ],
        ),
        migrations.AddField(
            model_name='student',
            name='student_class',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='src.studentclass'),
        ),
    ]
