# Generated by Django 4.2 on 2023-10-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentbehaviouralassessment',
            name='days_absent',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentbehaviouralassessment',
            name='days_present',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentbehaviouralassessment',
            name='school_opened',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
