# Generated by Django 4.2.3 on 2023-12-03 05:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("src", "0004_alter_student_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentbehaviouralassessment",
            name="next_date_of_resumption",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
